import { chromium } from "playwright";

const browser = await chromium.launch();
const page = await browser.newPage();
const consoleErrors = [];
page.on("console", (m) => { if (m.type() === "error") consoleErrors.push(m.text().slice(0, 160)); });

await page.goto("http://localhost:5174");
await page.fill('input[type=email], form input', "presenter@itc.local");
await page.fill('input[type=password]', "demo");
await page.click("form button");

// Open the Company flow and register with demo evidence
await page.getByRole("button", { name: "Company", exact: true }).click();
await page.waitForTimeout(800);
await page.getByRole("button", { name: /register/i }).first().click();
await page.waitForSelector(".intake-modal", { timeout: 10000 });
await page.getByRole("button", { name: /fill demo survey/i }).click();
await page.waitForTimeout(1200);

const t0 = Date.now();
await page.getByRole("button", { name: /register and analyze with ai/i }).click();

// Wait for the live analysis to complete: draft response block + Generated by AI tags
let ok = false;
for (let i = 0; i < 40; i++) {
  await page.waitForTimeout(2000);
  const body = await page.textContent("body");
  if (/draft response/i.test(body) && /generated by ai/i.test(body) &&
      !/running live ai analysis/i.test(body)) { ok = true; break; }
}
const elapsed = ((Date.now() - t0) / 1000).toFixed(1);
const body = await page.textContent("body");

const report = {
  liveCompleted: ok,
  seconds: elapsed,
  fallbackNoticeShown: /unreachable right now/i.test(body),
  hasCompleteness: /completeness/i.test(body),
  hasExtractedFields: /extracted/i.test(body),
  hasFindings: /finding/i.test(body),
  hasDraft: /draft response/i.test(body),
  hasAiPick: (await page.locator(".ai-pick").count()) > 0,
  consoleErrors: consoleErrors.slice(0, 5),
};
await page.screenshot({ path: "demo/output/qa/liveai-run.png", fullPage: false });
console.log(JSON.stringify(report, null, 1));
await browser.close();
