import type {
  DemoScenario,
  DoohRule,
  KnowledgeSource,
  OntologyEntity,
  RuleSimulationContext,
} from "./intelligence-content";

export const extendedDoohOntology: OntologyEntity[] = [
  {
    id: "ONT-ZONE",
    name: { en: "Zone", ar: "منطقة" },
    layer: { en: "Operations", ar: "العمليات" },
    definition: { en: "A managed geographic cluster of assets with health, availability, demand, emergency priority and commercial packaging rules.", ar: "تجمع جغرافي مُدار من الأصول له صحة وتوفر وطلب وأولوية طوارئ وقواعد حزم تجارية." },
    examples: ["Abu Dhabi City", "Yas Island", "Airport corridor"],
    relationships: ["Asset", "Schedule item", "Emergency alert", "Marketplace lot"],
  },
  {
    id: "ONT-PACKAGE",
    name: { en: "Media package", ar: "حزمة إعلامية" },
    layer: { en: "Commercial", ar: "التجاري" },
    definition: { en: "A sellable bundle of zones, assets, impressions, formats, flight windows and constraints offered in the marketplace.", ar: "حزمة قابلة للبيع من المناطق والأصول والانطباعات والصيغ ونوافذ التشغيل والقيود المعروضة في السوق." },
    examples: ["Airport and premium roadside", "Downtown retail loop"],
    relationships: ["Bid", "Rate card", "Zone", "Campaign"],
  },
  {
    id: "ONT-SCHEDULE",
    name: { en: "Schedule slot", ar: "خانة جدولة" },
    layer: { en: "CMS", ar: "إدارة المحتوى" },
    definition: { en: "A planned playback reservation binding campaign, creative, asset group, daypart, priority and fallback logic.", ar: "حجز تشغيل مخطط يربط الحملة والتصميم ومجموعة الأصول والفترة اليومية والأولوية ومنطق الاحتياط." },
    examples: ["08:00 road safety rotation", "Weekend mall offer"],
    relationships: ["Submission", "Asset", "Proof-of-play", "Competitive separation"],
  },
  {
    id: "ONT-SERVICE-ORDER",
    name: { en: "Service order", ar: "أمر خدمة" },
    layer: { en: "Network and Devices", ar: "الشبكة والأجهزة" },
    definition: { en: "A maintenance task with priority, technician assignment, part dependencies, SLA, evidence and close-out state.", ar: "مهمة صيانة لها أولوية وتكليف فني وتبعيات قطع ومستوى خدمة وأدلة وحالة إغلاق." },
    examples: ["SO-8821 controller replacement", "SO-8837 PSU inspection"],
    relationships: ["Asset", "BoM component", "Purchase order", "Maintenance workbench"],
  },
  {
    id: "ONT-PURCHASE-ORDER",
    name: { en: "Purchase order", ar: "أمر شراء" },
    layer: { en: "Network and Devices", ar: "الشبكة والأجهزة" },
    definition: { en: "A procurement record for spare parts, supplier confirmation, expected delivery and operational dependency.", ar: "سجل شراء لقطع الغيار وتأكيد المورد وموعد التسليم المتوقع والتبعية التشغيلية." },
    examples: ["PO-4490 edge controller", "PO-4512 power supply"],
    relationships: ["BoM component", "Service order", "Supplier", "Asset"],
  },
  {
    id: "ONT-INVENTORY",
    name: { en: "Spare inventory", ar: "مخزون قطع الغيار" },
    layer: { en: "Network and Devices", ar: "الشبكة والأجهزة" },
    definition: { en: "Depot, reserved, in-transit and field stock levels mapped to compatible components and risk thresholds.", ar: "مستويات المخزون في المستودع والمحجوز والمنقول والميداني المرتبطة بالمكونات المتوافقة وحدود المخاطر." },
    examples: ["PSU-48V depot stock", "5G router warranty exchange"],
    relationships: ["Purchase order", "Service order", "Component"],
  },
  {
    id: "ONT-TELEMETRY",
    name: { en: "Telemetry event", ar: "حدث قياس" },
    layer: { en: "Edge and Compute", ar: "الحافة والحوسبة" },
    definition: { en: "A timestamped signal from screen, controller, router, sensor or edge runtime used for health, proof and prediction.", ar: "إشارة زمنية من الشاشة أو وحدة التحكم أو الراوتر أو الحساس أو تشغيل الحافة تُستخدم للصحة والإثبات والتنبؤ." },
    examples: ["temperature.warning", "playback.signed", "router.packet_loss"],
    relationships: ["Asset", "Proof-of-play", "Model", "Service order"],
  },
  {
    id: "ONT-INTEGRATION",
    name: { en: "Integration connector", ar: "موصل تكامل" },
    layer: { en: "Infrastructure", ar: "البنية التحتية" },
    definition: { en: "A governed data link to CMS, ERP, IoT broker, finance, media storage, identity or file import.", ar: "رابط بيانات محكوم مع إدارة المحتوى أو ERP أو وسيط إنترنت الأشياء أو المالية أو تخزين الوسائط أو الهوية أو استيراد الملفات." },
    examples: ["ERP purchase orders", "IoT telemetry broker"],
    relationships: ["Knowledge source", "Model", "Audit log", "Access role"],
  },
  {
    id: "ONT-MODEL",
    name: { en: "AI model", ar: "نموذج ذكاء اصطناعي" },
    layer: { en: "Models", ar: "النماذج" },
    definition: { en: "A versioned model used by MediaGPT for moderation, retrieval, forecasting, optimization, translation or anomaly detection.", ar: "نموذج بإصدار يستخدمه MediaGPT للمراجعة والاسترجاع والتوقع والتحسين والترجمة ورصد الشذوذ." },
    examples: ["MediaGPT Moderator", "MediaGPT Yield Optimizer"],
    relationships: ["Skill", "Knowledge source", "Rule", "Model run"],
  },
  {
    id: "ONT-SKILL",
    name: { en: "AI skill", ar: "مهارة ذكاء اصطناعي" },
    layer: { en: "Skills", ar: "المهارات" },
    definition: { en: "A reusable governed capability that takes workflow context and returns recommendation, evidence, action and audit metadata.", ar: "قدرة محكومة قابلة لإعادة الاستخدام تأخذ سياق سير العمل وتعيد توصية وأدلة وإجراء وبيانات تدقيق." },
    examples: ["Arabic parity checker", "BoM and PO recommender"],
    relationships: ["Model", "Rule", "Workflow", "Audit log"],
  },
  {
    id: "ONT-ROLE",
    name: { en: "Access role", ar: "دور صلاحية" },
    layer: { en: "Infrastructure", ar: "البنية التحتية" },
    definition: { en: "A profile with allowed pages, data scopes, governed actions, approval rights and notification routing.", ar: "ملف صلاحيات له صفحات ونطاقات بيانات وإجراءات محكومة وحقوق اعتماد وتوجيه إشعارات." },
    examples: ["ADMO reviewer", "Finance", "Technical owner", "Bidder"],
    relationships: ["Governed action", "Rule", "Notification", "Audit log"],
  },
  {
    id: "ONT-NOTIFICATION",
    name: { en: "Notification", ar: "إشعار" },
    layer: { en: "Workflow", ar: "سير العمل" },
    definition: { en: "A targeted event that tells the right profile that an action, approval, revision or exception is waiting.", ar: "حدث موجه يخبر الملف المناسب بأن إجراء أو اعتماد أو تعديل أو استثناء ينتظر." },
    examples: ["Bidder revision requested", "Finance approval pending"],
    relationships: ["Governed action", "Access role", "Campaign", "Alert"],
  },
  {
    id: "ONT-AUDIT-EVENT",
    name: { en: "Audit event", ar: "حدث تدقيق" },
    layer: { en: "Audit", ar: "التدقيق" },
    definition: { en: "An immutable record of user action, AI recommendation, rule hit, source citation and state change.", ar: "سجل غير قابل للتغيير لإجراء المستخدم وتوصية الذكاء الاصطناعي والقاعدة المطابقة والاستشهاد وتغيير الحالة." },
    examples: ["RULE-CMS-002 fired", "FIN-1200 approved"],
    relationships: ["Rule", "Knowledge source", "Governed action", "Profile"],
  },
  {
    id: "ONT-KNOWLEDGE-CHUNK",
    name: { en: "Knowledge chunk", ar: "مقطع معرفة" },
    layer: { en: "Intelligence", ar: "الذكاء" },
    definition: { en: "A retrievable passage with source, page, clause, sensitivity, embedding state and citation anchor.", ar: "مقطع قابل للاسترجاع له مصدر وصفحة وبند وحساسية وحالة فهرسة ومرساة استشهاد." },
    examples: ["Creative clause 3.2", "CAP field list"],
    relationships: ["Knowledge source", "AI answer", "Rule", "Citation"],
  },
  {
    id: "ONT-DATA-QUALITY",
    name: { en: "Data quality finding", ar: "ملاحظة جودة بيانات" },
    layer: { en: "Infrastructure", ar: "البنية التحتية" },
    definition: { en: "A detected missing, stale, conflicting or low-confidence field that can affect AI output or workflow execution.", ar: "حقل ناقص أو قديم أو متعارض أو منخفض الثقة قد يؤثر على مخرج الذكاء الاصطناعي أو تنفيذ سير العمل." },
    examples: ["Missing expiry", "Stale PO ETA", "Unmatched asset id"],
    relationships: ["Integration", "Rule", "Knowledge source", "Audit event"],
  },
];

export const extendedKnowledgeSources: KnowledgeSource[] = [
  {
    id: "KB-GOV-002",
    collectionId: "governance",
    title: { en: "Role-based access and delegation matrix", ar: "مصفوفة الصلاحيات والتفويض حسب الدور" },
    type: "Policy",
    status: "Indexed",
    owner: "Platform governance",
    version: "v1.1",
    effectiveDate: "2026-07-01",
    sensitivity: "Confidential",
    chunks: 530,
    lastIndexed: "Today 10:16",
    summary: { en: "Maps profiles to pages, approvals, AI actions, notifications and data visibility boundaries.", ar: "تربط الملفات بالصفحات والاعتمادات وإجراءات الذكاء الاصطناعي والإشعارات وحدود رؤية البيانات." },
    body: { en: "Operational users can execute workflow actions in their domain. Technical users manage intelligence, rules, integrations and edge compute. Bidders see only their campaigns, marketplace lots, messages and submission status.", ar: "ينفذ مستخدمو العمليات إجراءات سير العمل في نطاقهم. يدير المستخدمون التقنيون الذكاء والقواعد والتكاملات وحوسبة الحافة. يرى المزايدون حملاتهم فقط وفرص السوق والرسائل وحالة الطلب." },
    linkedEntities: ["ONT-ROLE", "ONT-ACTION", "ONT-NOTIFICATION"],
    tags: ["RBAC", "delegation", "profiles"],
    citations: ["Access matrix A1", "Delegated approvals A4"],
    usedBy: ["MediaGPT Orchestrator", "Access & Roles"],
  },
  {
    id: "KB-GOV-003",
    collectionId: "governance",
    title: { en: "ADMO civic tone and public-interest guide", ar: "دليل النبرة المدنية والمصلحة العامة لمكتب أبوظبي الإعلامي" },
    type: "Manual",
    status: "Indexed",
    owner: "ADMO communications",
    version: "v1.4",
    effectiveDate: "2026-06-20",
    sensitivity: "Internal",
    chunks: 486,
    lastIndexed: "Today 09:55",
    summary: { en: "Defines acceptable tone, restricted claims and language hierarchy for civic campaigns.", ar: "يحدد النبرة المقبولة والادعاءات المقيدة وتراتبية اللغة للحملات المدنية." },
    body: { en: "Public-interest campaigns should be direct, calm, Arabic-first and avoid commercial-style urgency unless the alert authority explicitly requires urgency.", ar: "ينبغي أن تكون حملات المصلحة العامة مباشرة وهادئة وعربية أولاً وأن تتجنب الإلحاح التجاري إلا إذا طلبت جهة التنبيه ذلك صراحة." },
    linkedEntities: ["ONT-SUBMISSION", "ONT-CREATIVE", "ONT-RULE"],
    tags: ["tone", "public interest", "Arabic first"],
    citations: ["Tone principles", "Civic campaign examples"],
    usedBy: ["MediaGPT Compliance", "MediaGPT Studio"],
  },
  {
    id: "KB-CRE-004",
    collectionId: "creative",
    title: { en: "Motion, animation and distraction thresholds", ar: "حدود الحركة والرسوم المتحركة والتشتت" },
    type: "Policy",
    status: "Indexed",
    owner: "CMS governance",
    version: "v1.5",
    effectiveDate: "2026-06-18",
    sensitivity: "Internal",
    chunks: 420,
    lastIndexed: "Today 08:51",
    summary: { en: "Rules for motion speed, flash, transition, dwell time and driver distraction by road class.", ar: "قواعد سرعة الحركة والوميض والانتقال ومدة العرض وتشتت السائق حسب فئة الطريق." },
    body: { en: "Highway assets should avoid rapid flashing, small moving text and high-contrast strobe transitions. Motion packs require an 8-second safe preview and a static fallback.", ar: "ينبغي أن تتجنب أصول الطرق السريعة الوميض السريع والنصوص الصغيرة المتحركة والانتقالات الوميضية عالية التباين. تحتاج حزم الحركة إلى معاينة آمنة مدتها 8 ثوانٍ وبديل ثابت." },
    linkedEntities: ["ONT-CREATIVE", "ONT-ASSET"],
    tags: ["motion", "flash", "driver distraction"],
    citations: ["Motion threshold M2", "Static fallback rule"],
    usedBy: ["MediaGPT Moderator", "MediaGPT Studio"],
  },
  {
    id: "KB-CRE-005",
    collectionId: "creative",
    title: { en: "Media asset library classification guide", ar: "دليل تصنيف مكتبة الأصول الإعلامية" },
    type: "Manual",
    status: "Indexed",
    owner: "Media operations",
    version: "v1.2",
    effectiveDate: "2026-06-24",
    sensitivity: "Internal",
    chunks: 355,
    lastIndexed: "Today 09:03",
    summary: { en: "Required metadata for images, video, audio, documents, rights, expiry, owner and campaign linkage.", ar: "البيانات الوصفية المطلوبة للصور والفيديو والصوت والمستندات والحقوق والانتهاء والمالك وربط الحملة." },
    body: { en: "Every media asset should carry type, dimensions, language, owner, rights state, expiry, content hash, source campaign and allowed formats.", ar: "يجب أن يحمل كل أصل إعلامي النوع والأبعاد واللغة والمالك وحالة الحقوق والانتهاء وبصمة المحتوى والحملة المصدرية والصيغ المسموحة." },
    linkedEntities: ["ONT-CREATIVE", "ONT-KNOWLEDGE"],
    tags: ["media library", "metadata", "rights"],
    citations: ["Metadata table", "Rights expiry field"],
    usedBy: ["MediaGPT Archive", "MediaGPT Moderator"],
  },
  {
    id: "KB-COM-003",
    collectionId: "commercial",
    title: { en: "Marketplace auction operating procedure", ar: "إجراء تشغيل مزادات السوق" },
    type: "SOP",
    status: "Indexed",
    owner: "Commercial operations",
    version: "v2.1",
    effectiveDate: "2026-07-01",
    sensitivity: "Restricted",
    chunks: 642,
    lastIndexed: "Today 10:00",
    summary: { en: "Bid packet completeness, floor validation, revision routing, bidder visibility and award notification.", ar: "اكتمال ملف العرض والتحقق من الحد الأدنى وتوجيه التعديلات ورؤية المزايد وإشعار الترسية." },
    body: { en: "Bids become real workflow objects once submitted: finance sees approvals, CMS sees creative packets, bidders see status and messages, and audit receives a signed event.", ar: "تصبح العروض كائنات سير عمل حقيقية بعد إرسالها: ترى المالية الاعتمادات، وترى إدارة المحتوى حزم التصميم، ويرى المزايدون الحالة والرسائل، ويتلقى التدقيق حدثاً موقعاً." },
    linkedEntities: ["ONT-BID", "ONT-PACKAGE", "ONT-ACTION"],
    tags: ["auction", "marketplace", "bid workflow"],
    citations: ["Bid packet checklist", "Award routing"],
    usedBy: ["MediaGPT Finance", "MediaGPT Orchestrator"],
  },
  {
    id: "KB-COM-004",
    collectionId: "commercial",
    title: { en: "Budget scenario and yield planning assumptions", ar: "افتراضات سيناريو الميزانية وتخطيط العائد" },
    type: "Dataset",
    status: "Indexed",
    owner: "Finance analytics",
    version: "v0.9",
    effectiveDate: "2026-07-01",
    sensitivity: "Restricted",
    chunks: 390,
    lastIndexed: "Today 09:46",
    summary: { en: "Demand pressure, strategic discount, fill rate, civic allocation and revenue optimization assumptions.", ar: "افتراضات ضغط الطلب والخصم الاستراتيجي ومعدل الإشغال والتخصيص المدني وتحسين الإيراد." },
    body: { en: "Scenario recommendations must explain whether the target is revenue, public-interest reach, inventory utilization, or competitive protection.", ar: "يجب أن توضح توصيات السيناريو ما إذا كان الهدف الإيراد أو وصول المصلحة العامة أو استخدام المخزون أو الحماية التنافسية." },
    linkedEntities: ["ONT-BID", "ONT-PACKAGE", "ONT-RULE"],
    tags: ["yield", "budget", "scenario"],
    citations: ["Scenario parameters", "Yield target definitions"],
    usedBy: ["MediaGPT Optimizer", "Financials"],
  },
  {
    id: "KB-EMG-003",
    collectionId: "emergency",
    title: { en: "Authority registry and escalation contacts", ar: "سجل الجهات المخولة وجهات التصعيد" },
    type: "Dataset",
    status: "Needs review",
    owner: "Emergency operations",
    version: "v1.0",
    effectiveDate: "2026-07-01",
    sensitivity: "Restricted",
    chunks: 218,
    lastIndexed: "Yesterday",
    summary: { en: "Allowed authorities, named approvers, escalation contacts and emergency scopes.", ar: "الجهات المسموحة والموافقون المسمون وجهات التصعيد ونطاقات الطوارئ." },
    body: { en: "Authority records must stay current. If a named authority is stale, MediaGPT should request manual validation instead of recommending broadcast.", ar: "يجب أن تبقى سجلات الجهات محدثة. إذا كانت الجهة المسماة قديمة، يجب أن يطلب MediaGPT تحققاً يدوياً بدل توصية البث." },
    linkedEntities: ["ONT-ALERT", "ONT-ROLE", "ONT-DATA-QUALITY"],
    tags: ["authority", "contacts", "stale data"],
    citations: ["Authority registry", "Manual validation rule"],
    usedBy: ["MediaGPT Orchestrator"],
  },
  {
    id: "KB-EMG-004",
    collectionId: "emergency",
    title: { en: "Emergency creative templates and safe layouts", ar: "قوالب تصاميم الطوارئ والتخطيطات الآمنة" },
    type: "Template",
    status: "Indexed",
    owner: "Control room",
    version: "v1.3",
    effectiveDate: "2026-06-30",
    sensitivity: "Internal",
    chunks: 284,
    lastIndexed: "Today 08:59",
    summary: { en: "Approved bilingual templates for warning, closure, safety, detour and all-clear messages.", ar: "قوالب ثنائية اللغة معتمدة للتحذير والإغلاق والسلامة والتحويلة وانتهاء الحالة." },
    body: { en: "Templates enforce Arabic-first order, authority logo placement, severity color, expiry time and a short instruction line.", ar: "تفرض القوالب العربية أولاً وموضع شعار الجهة ولون الشدة ووقت الانتهاء وسطر تعليمات قصير." },
    linkedEntities: ["ONT-ALERT", "ONT-CREATIVE"],
    tags: ["emergency template", "layout", "Arabic first"],
    citations: ["Template set E1", "Severity color table"],
    usedBy: ["MediaGPT Orchestrator", "MediaGPT Studio"],
  },
  {
    id: "KB-NET-003",
    collectionId: "network",
    title: { en: "Telemetry dictionary and fault taxonomy", ar: "قاموس القياسات وتصنيف الأعطال" },
    type: "Dataset",
    status: "Indexed",
    owner: "Network operations",
    version: "v2.2",
    effectiveDate: "2026-06-28",
    sensitivity: "Confidential",
    chunks: 910,
    lastIndexed: "Today 07:44",
    summary: { en: "Canonical telemetry fields, severity mapping, asset-health states and predictive maintenance labels.", ar: "حقول القياس القياسية وربط الشدة وحالات صحة الأصل وتسميات الصيانة التنبؤية." },
    body: { en: "Fault predictions should cite the telemetry signal, component, threshold, campaign impact and recommended work order action.", ar: "يجب أن تستشهد توقعات الأعطال بإشارة القياس والمكون والحد وتأثير الحملة وإجراء أمر العمل المقترح." },
    linkedEntities: ["ONT-TELEMETRY", "ONT-COMPONENT", "ONT-SERVICE-ORDER"],
    tags: ["telemetry", "fault", "prediction"],
    citations: ["Telemetry field list", "Fault severity matrix"],
    usedBy: ["MediaGPT Sentinel", "MediaGPT Maintainer"],
  },
  {
    id: "KB-NET-004",
    collectionId: "network",
    title: { en: "Asset BoQ, warranty and supplier catalogue", ar: "قائمة كميات الأصول والضمان وفهرس الموردين" },
    type: "Dataset",
    status: "Indexing",
    owner: "O&M administration",
    version: "v0.7",
    effectiveDate: "2026-07-01",
    sensitivity: "Confidential",
    chunks: 0,
    lastIndexed: "Indexing now",
    summary: { en: "Supplier, warranty, compatible part, lead time and exchange options for every critical component.", ar: "المورد والضمان والقطعة المتوافقة ومدة التوريد وخيارات الاستبدال لكل مكون حرج." },
    body: { en: "BoQ records should be expandable from the asset row so operations can see part status, warranty, PO ETA, SO stage and AI recommendation together.", ar: "ينبغي أن تكون سجلات الكميات قابلة للتوسيع من صف الأصل حتى ترى العمليات حالة القطعة والضمان وموعد أمر الشراء ومرحلة أمر الخدمة وتوصية الذكاء معاً." },
    linkedEntities: ["ONT-INVENTORY", "ONT-PURCHASE-ORDER", "ONT-SERVICE-ORDER"],
    tags: ["BoQ", "warranty", "supplier"],
    citations: ["Supplier catalogue", "Warranty compatibility"],
    usedBy: ["MediaGPT Maintainer"],
  },
  {
    id: "KB-POP-002",
    collectionId: "proof",
    title: { en: "Invoice settlement and make-good policy", ar: "سياسة تسوية الفواتير والتعويض الإعلاني" },
    type: "Policy",
    status: "Indexed",
    owner: "Finance and audit",
    version: "v1.4",
    effectiveDate: "2026-06-15",
    sensitivity: "Restricted",
    chunks: 365,
    lastIndexed: "Today 09:12",
    summary: { en: "How missing plays, degraded screens, make-good credits and billing holds are handled.", ar: "كيفية التعامل مع التشغيل الناقص والشاشات المتدهورة وأرصدة التعويض وتعليق الفوترة." },
    body: { en: "Settlement can proceed only when proof-of-play coverage and exception handling satisfy the campaign contract and finance policy.", ar: "لا تتم التسوية إلا عندما تلبي تغطية إثبات التشغيل ومعالجة الاستثناءات عقد الحملة وسياسة المالية." },
    linkedEntities: ["ONT-POP", "ONT-BID", "ONT-AUDIT-EVENT"],
    tags: ["settlement", "invoice", "make-good"],
    citations: ["Settlement hold rule", "Make-good credit schedule"],
    usedBy: ["MediaGPT Finance", "MediaGPT Proof-of-Play Reconciler"],
  },
  {
    id: "KB-INT-002",
    collectionId: "integrations",
    title: { en: "ERP procurement and service order contract", ar: "عقد بيانات ERP لأوامر الشراء والخدمة" },
    type: "Dataset",
    status: "Indexed",
    owner: "Technical Platform Owner",
    version: "v0.9",
    effectiveDate: "2026-07-01",
    sensitivity: "Confidential",
    chunks: 470,
    lastIndexed: "Today 10:02",
    summary: { en: "Field mapping for POs, SOs, supplier confirmation, expected delivery and service close-out.", ar: "ربط حقول أوامر الشراء والخدمة وتأكيد المورد والتسليم المتوقع وإغلاق الخدمة." },
    body: { en: "ERP updates should trigger notifications and refresh the asset BoM table so procurement risk is visible inside Network and Devices.", ar: "ينبغي أن تطلق تحديثات ERP إشعارات وتحدث جدول مكونات الأصل حتى تظهر مخاطر الشراء داخل الشبكة والأجهزة." },
    linkedEntities: ["ONT-INTEGRATION", "ONT-PURCHASE-ORDER", "ONT-SERVICE-ORDER"],
    tags: ["ERP", "PO", "SO"],
    citations: ["PO mapping", "SO close-out event"],
    usedBy: ["MediaGPT Maintainer", "Integrations"],
  },
  {
    id: "KB-INT-003",
    collectionId: "integrations",
    title: { en: "IoT broker and edge telemetry contract", ar: "عقد وسيط إنترنت الأشياء وقياسات الحافة" },
    type: "Dataset",
    status: "Indexed",
    owner: "Technical Platform Owner",
    version: "v1.2",
    effectiveDate: "2026-06-26",
    sensitivity: "Confidential",
    chunks: 590,
    lastIndexed: "Today 09:38",
    summary: { en: "Telemetry topics, replay policy, signed event contract and stale signal handling.", ar: "مواضيع القياس وسياسة إعادة التشغيل وعقد الحدث الموقع والتعامل مع الإشارات القديمة." },
    body: { en: "Signed playback, temperature, connectivity, player and cabinet events feed health, proof-of-play and predictive maintenance models.", ar: "تغذي أحداث التشغيل الموقعة والحرارة والاتصال والمشغل والخزانة نماذج الصحة وإثبات التشغيل والصيانة التنبؤية." },
    linkedEntities: ["ONT-INTEGRATION", "ONT-TELEMETRY", "ONT-POP"],
    tags: ["IoT", "edge", "telemetry"],
    citations: ["Topic map", "Signed event contract"],
    usedBy: ["MediaGPT Sentinel", "MediaGPT Proof-of-Play Reconciler"],
  },
  {
    id: "KB-AI-002",
    collectionId: "mediagpt",
    title: { en: "MediaGPT skill orchestration runbook", ar: "دليل تنسيق مهارات MediaGPT" },
    type: "Runbook",
    status: "Indexed",
    owner: "AI product governance",
    version: "v1.1",
    effectiveDate: "2026-07-01",
    sensitivity: "Confidential",
    chunks: 610,
    lastIndexed: "Today 10:05",
    summary: { en: "How agents call skills, collect citations, propose actions and hand work to humans.", ar: "كيف يستدعي الوكلاء المهارات ويجمعون الاستشهادات ويقترحون الإجراءات ويسلمون العمل للبشر." },
    body: { en: "Every skill run returns a typed recommendation: finding, severity, citations, matched rules, allowed actions, required profile and audit payload.", ar: "يعيد كل تشغيل مهارة توصية مهيكلة: الملاحظة، الشدة، الاستشهادات، القواعد المطابقة، الإجراءات المسموحة، الملف المطلوب، وحمولة التدقيق." },
    linkedEntities: ["ONT-SKILL", "ONT-MODEL", "ONT-ACTION"],
    tags: ["skills", "orchestration", "audit"],
    citations: ["Skill output schema", "Human handoff"],
    usedBy: ["All MediaGPT agents"],
  },
  {
    id: "KB-AI-003",
    collectionId: "mediagpt",
    title: { en: "Model evaluation, token and cost policy", ar: "سياسة تقييم النماذج والرموز والتكلفة" },
    type: "Policy",
    status: "Indexed",
    owner: "AI product governance",
    version: "v1.0",
    effectiveDate: "2026-07-01",
    sensitivity: "Confidential",
    chunks: 340,
    lastIndexed: "Today 10:09",
    summary: { en: "Tracks model quality, latency, token use, cost center, drift and fallback requirements.", ar: "تتبع جودة النموذج والكمون واستخدام الرموز ومركز التكلفة والانحراف ومتطلبات البديل." },
    body: { en: "Operational AI runs must expose model, token estimate, latency band, confidence, fallback and whether the action is recommendation-only or execution-capable.", ar: "يجب أن تعرض تشغيلات الذكاء التشغيلية النموذج وتقدير الرموز ونطاق الكمون والثقة والبديل وما إذا كان الإجراء توصية فقط أو قابلاً للتنفيذ." },
    linkedEntities: ["ONT-MODEL", "ONT-SKILL", "ONT-AUDIT-EVENT"],
    tags: ["model", "tokens", "cost", "evaluation"],
    citations: ["Evaluation matrix", "Cost attribution"],
    usedBy: ["Model Center", "Skill Runs"],
  },
];

export const extendedDoohRules: DoohRule[] = [
  {
    id: "RULE-CMS-004",
    title: { en: "Motion safety on driving corridors", ar: "سلامة الحركة على ممرات القيادة" },
    family: "Creative policy",
    scope: "Video and motion creative",
    workflowStage: "AI Screening",
    mode: "Enforce",
    status: "Active",
    severity: "High",
    enabled: true,
    condition: { en: "Creative uses flashing, fast scrolling text or motion above road-class threshold.", ar: "التصميم يستخدم وميضاً أو نصاً متحركاً سريعاً أو حركة أعلى من حد فئة الطريق." },
    action: { en: "Block highway playback and request safe motion version or static fallback.", ar: "منع التشغيل على الطريق السريع وطلب نسخة حركة آمنة أو بديل ثابت." },
    recommendedAction: "Request bidder changes",
    owner: "CMS governance",
    sourceId: "KB-CRE-004",
    overridePolicy: { en: "No override for flashing risk on highway assets.", ar: "لا تجاوز لمخاطر الوميض على أصول الطرق السريعة." },
    effectiveDate: "2026-06-18",
    version: "v1.5",
    aiEffect: { en: "MediaGPT flags unsafe motion and can draft the revision note.", ar: "يرصد MediaGPT الحركة غير الآمنة ويمكنه إعداد ملاحظة التعديل." },
    linkedEntities: ["ONT-CREATIVE", "ONT-ASSET"],
    testCases: [{ input: "Video with strobe effect on 100 km/h corridor", expected: "Block highway playback" }],
  },
  {
    id: "RULE-CMS-005",
    title: { en: "Media asset metadata completeness", ar: "اكتمال بيانات الأصل الإعلامي" },
    family: "Media library",
    scope: "Media library",
    workflowStage: "Intake",
    mode: "Enforce",
    status: "Active",
    severity: "Medium",
    enabled: true,
    condition: { en: "Asset lacks owner, rights state, expiry, dimensions, language or content hash.", ar: "الأصل يفتقد المالك أو حالة الحقوق أو الانتهاء أو الأبعاد أو اللغة أو بصمة المحتوى." },
    action: { en: "Keep asset out of scheduling until metadata is completed.", ar: "إبقاء الأصل خارج الجدولة حتى تكتمل بياناته." },
    recommendedAction: "Complete media metadata",
    owner: "Media operations",
    sourceId: "KB-CRE-005",
    overridePolicy: { en: "Media operations may mark temporary internal use for civic drafts only.", ar: "يمكن لعمليات الإعلام تعيين استخدام داخلي مؤقت للمسودات المدنية فقط." },
    effectiveDate: "2026-06-24",
    version: "v1.2",
    aiEffect: { en: "MediaGPT Archive identifies missing metadata and proposes values.", ar: "يحدد MediaGPT Archive البيانات الناقصة ويقترح القيم." },
    linkedEntities: ["ONT-CREATIVE", "ONT-KNOWLEDGE"],
    testCases: [{ input: "Image has no rights expiry", expected: "Block scheduling" }],
  },
  {
    id: "RULE-GOV-001",
    title: { en: "Role must allow governed action", ar: "الدور يجب أن يسمح بالإجراء المحكوم" },
    family: "Access governance",
    scope: "All workflows",
    workflowStage: "Action execution",
    mode: "Enforce",
    status: "Strict",
    severity: "Critical",
    enabled: true,
    condition: { en: "Profile attempts to execute an action outside its delegated authority.", ar: "الملف يحاول تنفيذ إجراء خارج صلاحياته المفوضة." },
    action: { en: "Hide or disable the action and route to the appropriate approver.", ar: "إخفاء أو تعطيل الإجراء وتوجيهه إلى المعتمد المناسب." },
    recommendedAction: "Route to approver",
    owner: "Platform governance",
    sourceId: "KB-GOV-002",
    overridePolicy: { en: "No UI override; access must be changed in Access & Roles.", ar: "لا تجاوز من الواجهة؛ يجب تغيير الصلاحية في الوصول والأدوار." },
    effectiveDate: "2026-07-01",
    version: "v1.1",
    aiEffect: { en: "MediaGPT can recommend handoff but not execute blocked actions.", ar: "يمكن لـ MediaGPT اقتراح التسليم ولا ينفذ الإجراءات المحظورة." },
    linkedEntities: ["ONT-ROLE", "ONT-ACTION"],
    testCases: [{ input: "Bidder tries to approve emergency broadcast", expected: "Block" }],
  },
  {
    id: "RULE-GOV-002",
    title: { en: "Civic tone for public-interest messages", ar: "النبرة المدنية لرسائل المصلحة العامة" },
    family: "Governance",
    scope: "Civic campaigns and emergency messages",
    workflowStage: "Human Moderation",
    mode: "Recommend",
    status: "Active",
    severity: "Medium",
    enabled: true,
    condition: { en: "Public-interest copy uses promotional urgency, ambiguous authority or unclear instruction.", ar: "نص المصلحة العامة يستخدم إلحاحاً ترويجياً أو جهة غامضة أو تعليمات غير واضحة." },
    action: { en: "Recommend calmer Arabic-first copy and authority clarification.", ar: "اقتراح نص أهدأ بالعربية أولاً وتوضيح الجهة." },
    recommendedAction: "Rewrite copy",
    owner: "ADMO communications",
    sourceId: "KB-GOV-003",
    overridePolicy: { en: "Communications lead may accept alternate tone with reason.", ar: "يمكن لقائد الاتصالات قبول نبرة بديلة مع سبب." },
    effectiveDate: "2026-06-20",
    version: "v1.4",
    aiEffect: { en: "MediaGPT Compliance suggests revised copy for reviewer approval.", ar: "يقترح MediaGPT Compliance نصاً معدلاً لاعتماد المراجع." },
    linkedEntities: ["ONT-CREATIVE", "ONT-ALERT"],
    testCases: [{ input: "Road closure message says limited-time now", expected: "Recommend rewrite" }],
  },
  {
    id: "RULE-COM-003",
    title: { en: "Bid packet completeness before award", ar: "اكتمال ملف العرض قبل الترسية" },
    family: "Commercial eligibility",
    scope: "Marketplace bids",
    workflowStage: "Marketplace submission",
    mode: "Enforce",
    status: "Active",
    severity: "High",
    enabled: true,
    condition: { en: "Bid is missing creative, rights declaration, budget, dates, contact or package selection.", ar: "العرض يفتقد التصميم أو تصريح الحقوق أو الميزانية أو التواريخ أو جهة الاتصال أو اختيار الحزمة." },
    action: { en: "Accept as draft only; do not route to finance or CMS until complete.", ar: "قبوله كمسودة فقط وعدم توجيهه للمالية أو إدارة المحتوى حتى يكتمل." },
    recommendedAction: "Complete bid packet",
    owner: "Commercial operations",
    sourceId: "KB-COM-003",
    overridePolicy: { en: "No award override for incomplete packet.", ar: "لا ترسية مع ملف غير مكتمل." },
    effectiveDate: "2026-07-01",
    version: "v2.1",
    aiEffect: { en: "MediaGPT checks bidder form completeness before creating workflow records.", ar: "يفحص MediaGPT اكتمال نموذج المزايد قبل إنشاء سجلات سير العمل." },
    linkedEntities: ["ONT-BID", "ONT-SUBMISSION"],
    testCases: [{ input: "Bid has budget but no creative rights declaration", expected: "Draft only" }],
  },
  {
    id: "RULE-COM-004",
    title: { en: "Scenario recommendation must state objective", ar: "توصية السيناريو يجب أن تحدد الهدف" },
    family: "Commercial optimization",
    scope: "Financial scenarios",
    workflowStage: "Scenario planning",
    mode: "Enforce",
    status: "Active",
    severity: "Medium",
    enabled: true,
    condition: { en: "AI recommends target bid or budget without stating revenue, reach, utilization or protection objective.", ar: "الذكاء الاصطناعي يوصي بهدف عرض أو ميزانية دون تحديد الإيراد أو الوصول أو الاستخدام أو الحماية." },
    action: { en: "Regenerate scenario with objective, assumptions and sensitivity.", ar: "إعادة توليد السيناريو مع الهدف والافتراضات والحساسية." },
    recommendedAction: "Regenerate scenario",
    owner: "Finance analytics",
    sourceId: "KB-COM-004",
    overridePolicy: { en: "Finance user may save only after selecting objective.", ar: "لا يحفظ مستخدم المالية إلا بعد اختيار الهدف." },
    effectiveDate: "2026-07-01",
    version: "v0.9",
    aiEffect: { en: "Controls Financials scenario panel and exported recommendations.", ar: "يضبط لوحة سيناريو المالية والتوصيات المصدرة." },
    linkedEntities: ["ONT-BID", "ONT-ACTION"],
    testCases: [{ input: "Recommended target AED 300k with no objective", expected: "Regenerate scenario" }],
  },
  {
    id: "RULE-EMG-003",
    title: { en: "Authority registry freshness", ar: "حداثة سجل الجهات المخولة" },
    family: "Emergency override",
    scope: "Alerts and emergencies",
    workflowStage: "Verification",
    mode: "Enforce",
    status: "Strict",
    severity: "Critical",
    enabled: true,
    condition: { en: "Named authority or contact record is stale, missing or outside approved scope.", ar: "سجل الجهة أو جهة الاتصال قديم أو مفقود أو خارج النطاق المعتمد." },
    action: { en: "Require manual authority validation before broadcast.", ar: "طلب تحقق يدوي من الجهة قبل البث." },
    recommendedAction: "Validate authority",
    owner: "Emergency operations",
    sourceId: "KB-EMG-003",
    overridePolicy: { en: "Duty officer and supervisor must record manual confirmation.", ar: "يجب أن يسجل ضابط المناوبة والمشرف التأكيد اليدوي." },
    effectiveDate: "2026-07-01",
    version: "v1.0",
    aiEffect: { en: "MediaGPT labels stale authority data instead of pretending certainty.", ar: "يسمي MediaGPT بيانات الجهة القديمة بدل ادعاء اليقين." },
    linkedEntities: ["ONT-ALERT", "ONT-DATA-QUALITY"],
    testCases: [{ input: "Authority contact not updated for 120 days", expected: "Manual validation" }],
  },
  {
    id: "RULE-EMG-004",
    title: { en: "Emergency template must match criticality", ar: "قالب الطوارئ يجب أن يطابق الشدة" },
    family: "Emergency creative",
    scope: "Emergency alert creative",
    workflowStage: "Payload validation",
    mode: "Enforce",
    status: "Active",
    severity: "High",
    enabled: true,
    condition: { en: "Template severity, color, expiry or instruction line does not match alert criticality.", ar: "شدة القالب أو اللون أو الانتهاء أو سطر التعليمات لا يطابق درجة التنبيه." },
    action: { en: "Switch to approved template and request operator confirmation.", ar: "التحويل إلى قالب معتمد وطلب تأكيد المشغل." },
    recommendedAction: "Apply emergency template",
    owner: "Control room",
    sourceId: "KB-EMG-004",
    overridePolicy: { en: "Operator may edit wording, not remove required fields.", ar: "يمكن للمشغل تعديل الصياغة ولا يزيل الحقول المطلوبة." },
    effectiveDate: "2026-06-30",
    version: "v1.3",
    aiEffect: { en: "MediaGPT can fill the alert layout before broadcast approval.", ar: "يمكن لـ MediaGPT ملء تخطيط التنبيه قبل اعتماد البث." },
    linkedEntities: ["ONT-ALERT", "ONT-CREATIVE"],
    testCases: [{ input: "Critical alert shown in minor template", expected: "Apply critical template" }],
  },
  {
    id: "RULE-NET-003",
    title: { en: "Telemetry stale signal quarantine", ar: "عزل إشارات القياس القديمة" },
    family: "Network maintenance",
    scope: "Edge telemetry",
    workflowStage: "Health monitoring",
    mode: "Monitor",
    status: "Active",
    severity: "Medium",
    enabled: true,
    condition: { en: "Telemetry for a live asset is stale beyond the configured freshness window.", ar: "قياسات أصل مباشر قديمة بعد نافذة الحداثة المحددة." },
    action: { en: "Mark data confidence low, request edge refresh and avoid automated proof decisions.", ar: "تعليم ثقة البيانات كمنخفضة وطلب تحديث الحافة وتجنب قرارات الإثبات الآلية." },
    recommendedAction: "Refresh edge telemetry",
    owner: "Network operations",
    sourceId: "KB-NET-003",
    overridePolicy: { en: "Network lead may confirm health manually until telemetry returns.", ar: "يمكن لقائد الشبكة تأكيد الصحة يدوياً حتى تعود القياسات." },
    effectiveDate: "2026-06-28",
    version: "v2.2",
    aiEffect: { en: "MediaGPT Sentinel cites low confidence before recommending action.", ar: "يستشهد MediaGPT Sentinel بانخفاض الثقة قبل توصية الإجراء." },
    linkedEntities: ["ONT-TELEMETRY", "ONT-DATA-QUALITY"],
    testCases: [{ input: "No telemetry for 25 minutes on live asset", expected: "Low confidence and refresh" }],
  },
  {
    id: "RULE-NET-004",
    title: { en: "Warranty-first replacement path", ar: "مسار الاستبدال بالضمان أولاً" },
    family: "Network maintenance",
    scope: "Spare parts and service orders",
    workflowStage: "Procurement",
    mode: "Recommend",
    status: "Active",
    severity: "Medium",
    enabled: true,
    condition: { en: "Faulty component is under warranty and compatible exchange is available.", ar: "المكون المعطل تحت الضمان وتوجد قطعة استبدال متوافقة." },
    action: { en: "Recommend warranty exchange before opening paid PO.", ar: "اقتراح الاستبدال بالضمان قبل فتح أمر شراء مدفوع." },
    recommendedAction: "Use warranty exchange",
    owner: "O&M administration",
    sourceId: "KB-NET-004",
    overridePolicy: { en: "Paid PO allowed only with supplier rejection or SLA breach.", ar: "يسمح بأمر شراء مدفوع فقط عند رفض المورد أو خرق مستوى الخدمة." },
    effectiveDate: "2026-07-01",
    version: "v0.7",
    aiEffect: { en: "MediaGPT Maintainer recommends lower-cost repair path.", ar: "يوصي MediaGPT Maintainer بمسار إصلاح أقل تكلفة." },
    linkedEntities: ["ONT-INVENTORY", "ONT-PURCHASE-ORDER"],
    testCases: [{ input: "5G router failed under warranty", expected: "Warranty exchange" }],
  },
  {
    id: "RULE-POP-002",
    title: { en: "Make-good required for missed contracted plays", ar: "تعويض إعلاني مطلوب للتشغيل الفائت المتعاقد عليه" },
    family: "Proof and audit",
    scope: "Published campaigns",
    workflowStage: "Reconciliation",
    mode: "Recommend",
    status: "Active",
    severity: "Medium",
    enabled: true,
    condition: { en: "Proof coverage is below contracted threshold after excluding approved emergency overrides.", ar: "تغطية الإثبات أقل من الحد المتعاقد عليه بعد استبعاد تجاوزات الطوارئ المعتمدة." },
    action: { en: "Recommend make-good slots or invoice credit.", ar: "اقتراح خانات تعويض أو رصيد فاتورة." },
    recommendedAction: "Offer make-good",
    owner: "Finance and audit",
    sourceId: "KB-POP-002",
    overridePolicy: { en: "Finance may close only with client-accepted make-good or credit.", ar: "تغلق المالية فقط مع تعويض أو رصيد مقبول من العميل." },
    effectiveDate: "2026-06-15",
    version: "v1.4",
    aiEffect: { en: "MediaGPT Finance calculates settlement impact.", ar: "يحسب MediaGPT Finance أثر التسوية." },
    linkedEntities: ["ONT-POP", "ONT-BID"],
    testCases: [{ input: "97% proof coverage against 99% contract", expected: "Offer make-good" }],
  },
  {
    id: "RULE-INT-001",
    title: { en: "Integration update must create workflow notification", ar: "تحديث التكامل يجب أن ينشئ إشعار سير عمل" },
    family: "Infrastructure",
    scope: "ERP, CMS and IoT integrations",
    workflowStage: "Data ingestion",
    mode: "Enforce",
    status: "Active",
    severity: "Medium",
    enabled: true,
    condition: { en: "External update changes PO ETA, SO state, campaign status or asset health without notifying owner.", ar: "تحديث خارجي يغير موعد أمر الشراء أو حالة أمر الخدمة أو حالة الحملة أو صحة الأصل دون إشعار المالك." },
    action: { en: "Create notification and audit event for the responsible profile.", ar: "إنشاء إشعار وحدث تدقيق للملف المسؤول." },
    recommendedAction: "Notify owner",
    owner: "Technical Platform Owner",
    sourceId: "KB-INT-002",
    overridePolicy: { en: "No silent state changes for operational records.", ar: "لا تغييرات صامتة لحالة السجلات التشغيلية." },
    effectiveDate: "2026-07-01",
    version: "v0.9",
    aiEffect: { en: "MediaGPT sees fresh state and users see why work moved.", ar: "يرى MediaGPT الحالة الحديثة ويرى المستخدمون سبب انتقال العمل." },
    linkedEntities: ["ONT-INTEGRATION", "ONT-NOTIFICATION", "ONT-AUDIT-EVENT"],
    testCases: [{ input: "ERP changes PO ETA", expected: "Notify O&M admin" }],
  },
  {
    id: "RULE-INT-002",
    title: { en: "Signed playback event required from edge", ar: "حدث تشغيل موقع مطلوب من الحافة" },
    family: "Infrastructure",
    scope: "IoT and edge telemetry",
    workflowStage: "Edge Play",
    mode: "Enforce",
    status: "Strict",
    severity: "High",
    enabled: true,
    condition: { en: "Playback event arrives without valid edge signature, creative hash or asset id.", ar: "حدث التشغيل يصل دون توقيع حافة صالح أو بصمة تصميم أو معرف أصل." },
    action: { en: "Reject event for proof-of-play and create telemetry exception.", ar: "رفض الحدث لإثبات التشغيل وإنشاء استثناء قياس." },
    recommendedAction: "Open telemetry exception",
    owner: "Technical Platform Owner",
    sourceId: "KB-INT-003",
    overridePolicy: { en: "No proof override without signed event or audit waiver.", ar: "لا تجاوز للإثبات دون حدث موقع أو تنازل تدقيق." },
    effectiveDate: "2026-06-26",
    version: "v1.2",
    aiEffect: { en: "Protects proof-of-play and settlement logic.", ar: "يحمي منطق إثبات التشغيل والتسوية." },
    linkedEntities: ["ONT-TELEMETRY", "ONT-POP"],
    testCases: [{ input: "Playback event has no signature", expected: "Reject proof event" }],
  },
  {
    id: "RULE-AI-002",
    title: { en: "Skill run must declare model and cost metadata", ar: "تشغيل المهارة يجب أن يعلن النموذج وبيانات التكلفة" },
    family: "AI governance",
    scope: "All MediaGPT skills",
    workflowStage: "Skill run",
    mode: "Enforce",
    status: "Active",
    severity: "Medium",
    enabled: true,
    condition: { en: "Skill result omits model name, version, token estimate, latency or fallback.", ar: "نتيجة المهارة لا تتضمن اسم النموذج أو الإصدار أو تقدير الرموز أو الكمون أو البديل." },
    action: { en: "Show result as draft and block operational execution until metadata is complete.", ar: "عرض النتيجة كمسودة ومنع التنفيذ التشغيلي حتى تكتمل البيانات." },
    recommendedAction: "Complete AI run metadata",
    owner: "AI product governance",
    sourceId: "KB-AI-003",
    overridePolicy: { en: "No override for state-changing AI actions.", ar: "لا تجاوز لإجراءات الذكاء التي تغير حالة المنصة." },
    effectiveDate: "2026-07-01",
    version: "v1.0",
    aiEffect: { en: "Keeps Model Center and Skill Runs auditable.", ar: "يبقي مركز النماذج وتشغيل المهارات قابلين للتدقيق." },
    linkedEntities: ["ONT-SKILL", "ONT-MODEL", "ONT-AUDIT-EVENT"],
    testCases: [{ input: "Skill output has no model version", expected: "Draft only" }],
  },
];

export const extendedRuleSimulationContexts: RuleSimulationContext[] = [
  {
    id: "SIM-CMS-MOTION",
    label: { en: "CMS: unsafe motion pack", ar: "إدارة المحتوى: حزمة حركة غير آمنة" },
    type: "Submission",
    input: { en: "Video creative uses fast flashes for a highway gateway asset.", ar: "تصميم فيديو يستخدم ومضات سريعة لأصل بوابة طريق سريع." },
    matchingRuleIds: ["RULE-CMS-004", "RULE-AI-001"],
    citedSourceIds: ["KB-CRE-004", "KB-AI-001"],
    recommendation: { en: "Block highway playback and request static fallback or safe motion version.", ar: "منع التشغيل على الطريق السريع وطلب بديل ثابت أو نسخة حركة آمنة." },
    action: { en: "Request bidder changes", ar: "طلب تعديلات من المعلن" },
    tone: "danger",
  },
  {
    id: "SIM-CMS-METADATA",
    label: { en: "Media library: missing rights expiry", ar: "مكتبة الوسائط: انتهاء الحقوق مفقود" },
    type: "Submission",
    input: { en: "A campaign image has dimensions and owner, but no rights expiry.", ar: "صورة الحملة لها أبعاد ومالك، لكنها بلا تاريخ انتهاء حقوق." },
    matchingRuleIds: ["RULE-CMS-005", "RULE-CMS-003"],
    citedSourceIds: ["KB-CRE-005", "KB-CRE-003"],
    recommendation: { en: "Keep asset out of scheduling and request missing rights metadata.", ar: "إبقاء الأصل خارج الجدولة وطلب بيانات الحقوق الناقصة." },
    action: { en: "Complete media metadata", ar: "استكمال بيانات الأصل الإعلامي" },
    tone: "warn",
  },
  {
    id: "SIM-GOV-RBAC",
    label: { en: "Governance: wrong profile action", ar: "الحوكمة: إجراء من ملف غير مخول" },
    type: "Schedule",
    input: { en: "A bidder attempts to approve emergency broadcast from marketplace context.", ar: "مزايد يحاول اعتماد بث طوارئ من سياق السوق." },
    matchingRuleIds: ["RULE-GOV-001"],
    citedSourceIds: ["KB-GOV-002"],
    recommendation: { en: "Block action and route to Control Room duty officer.", ar: "منع الإجراء وتوجيهه إلى ضابط المناوبة في غرفة التحكم." },
    action: { en: "Route to approver", ar: "توجيه إلى المعتمد" },
    tone: "danger",
  },
  {
    id: "SIM-EMG-TEMPLATE",
    label: { en: "Emergency: wrong severity template", ar: "الطوارئ: قالب شدة غير مطابق" },
    type: "Emergency",
    input: { en: "Critical weather alert uses minor template and has no expiry line.", ar: "تنبيه طقس حرج يستخدم قالباً بسيطاً ولا يحتوي سطر انتهاء." },
    matchingRuleIds: ["RULE-EMG-004", "RULE-EMG-002"],
    citedSourceIds: ["KB-EMG-004", "KB-EMG-002"],
    recommendation: { en: "Apply critical template and generate expiry for operator confirmation.", ar: "تطبيق قالب حرج وتوليد انتهاء لتأكيد المشغل." },
    action: { en: "Apply emergency template", ar: "تطبيق قالب الطوارئ" },
    tone: "warn",
  },
  {
    id: "SIM-NET-WARRANTY",
    label: { en: "Network: warranty exchange available", ar: "الشبكة: استبدال الضمان متاح" },
    type: "Asset",
    input: { en: "5G router failed, warranty is active and exchange part exists.", ar: "تعطل راوتر 5G والضمان نشط وقطعة الاستبدال موجودة." },
    matchingRuleIds: ["RULE-NET-004", "RULE-NET-001"],
    citedSourceIds: ["KB-NET-004", "KB-NET-001"],
    recommendation: { en: "Use warranty exchange and avoid paid PO unless SLA is breached.", ar: "استخدام استبدال الضمان وتجنب أمر شراء مدفوع إلا عند خرق مستوى الخدمة." },
    action: { en: "Use warranty exchange", ar: "استخدام استبدال الضمان" },
    tone: "good",
  },
  {
    id: "SIM-NET-STALE",
    label: { en: "Network: stale telemetry", ar: "الشبكة: قياسات قديمة" },
    type: "Asset",
    input: { en: "Live asset has no telemetry update for 25 minutes while campaign is playing.", ar: "أصل مباشر لا يملك تحديث قياسات منذ 25 دقيقة أثناء تشغيل حملة." },
    matchingRuleIds: ["RULE-NET-003", "RULE-INT-001"],
    citedSourceIds: ["KB-NET-003", "KB-INT-003"],
    recommendation: { en: "Mark confidence low, refresh edge telemetry and notify Network operations.", ar: "تعيين الثقة منخفضة وتحديث قياسات الحافة وإشعار عمليات الشبكة." },
    action: { en: "Refresh edge telemetry", ar: "تحديث قياسات الحافة" },
    tone: "warn",
  },
  {
    id: "SIM-POP-MAKEGOOD",
    label: { en: "Proof: make-good due", ar: "الإثبات: تعويض مطلوب" },
    type: "Proof",
    input: { en: "Proof coverage is 97% against a 99% contract threshold.", ar: "تغطية الإثبات 97% مقابل حد تعاقدي 99%." },
    matchingRuleIds: ["RULE-POP-002", "RULE-POP-001"],
    citedSourceIds: ["KB-POP-002", "KB-POP-001"],
    recommendation: { en: "Offer make-good slots or invoice credit and keep audit exception open.", ar: "اقتراح خانات تعويض أو رصيد فاتورة وإبقاء استثناء التدقيق مفتوحاً." },
    action: { en: "Offer make-good", ar: "تقديم تعويض إعلاني" },
    tone: "warn",
  },
  {
    id: "SIM-AI-METADATA",
    label: { en: "AI: missing run metadata", ar: "الذكاء: بيانات تشغيل ناقصة" },
    type: "Submission",
    input: { en: "A skill output recommends approval but omits model version and citations.", ar: "نتيجة مهارة توصي بالاعتماد لكنها لا تتضمن إصدار النموذج أو الاستشهادات." },
    matchingRuleIds: ["RULE-AI-001", "RULE-AI-002"],
    citedSourceIds: ["KB-AI-001", "KB-AI-003"],
    recommendation: { en: "Hide operational action and regenerate governed answer.", ar: "إخفاء الإجراء التشغيلي وإعادة توليد إجابة محكومة." },
    action: { en: "Regenerate governed answer", ar: "إعادة توليد إجابة محكومة" },
    tone: "danger",
  },
];

export const extendedDemoScenarios: DemoScenario[] = [
  {
    id: "SCN-009",
    title: { en: "Unsafe video creative is returned to bidder", ar: "إرجاع تصميم فيديو غير آمن إلى المعلن" },
    persona: "CMS reviewer",
    workflow: "CMS submissions",
    trigger: { en: "Motion pack exceeds driving corridor thresholds.", ar: "حزمة الحركة تتجاوز حدود ممر القيادة." },
    rules: ["RULE-CMS-004", "RULE-AI-001"],
    sources: ["KB-CRE-004", "KB-AI-001"],
    outcome: { en: "Campaign cannot be scheduled on highway assets until safe version is uploaded.", ar: "لا يمكن جدولة الحملة على أصول الطريق السريع حتى يتم رفع نسخة آمنة." },
    nextAction: { en: "Request bidder changes", ar: "طلب تعديلات من المعلن" },
    status: "Ready",
  },
  {
    id: "SCN-010",
    title: { en: "Media library asset is blocked for missing rights metadata", ar: "حظر أصل مكتبة الوسائط بسبب نقص بيانات الحقوق" },
    persona: "Media operations",
    workflow: "CMS media library",
    trigger: { en: "Image has no expiry and no source campaign link.", ar: "الصورة لا تملك تاريخ انتهاء ولا رابط حملة مصدرية." },
    rules: ["RULE-CMS-005", "RULE-CMS-003"],
    sources: ["KB-CRE-005", "KB-CRE-003"],
    outcome: { en: "Asset remains searchable but unavailable for scheduling.", ar: "يبقى الأصل قابلاً للبحث لكنه غير متاح للجدولة." },
    nextAction: { en: "Complete media metadata", ar: "استكمال بيانات الأصل الإعلامي" },
    status: "Ready",
  },
  {
    id: "SCN-011",
    title: { en: "Bidder action is blocked by RBAC", ar: "منع إجراء المزايد بسبب الصلاحيات" },
    persona: "Bidder",
    workflow: "Marketplace",
    trigger: { en: "External bidder tries to access internal emergency approval.", ar: "مزايد خارجي يحاول الوصول إلى اعتماد طوارئ داخلي." },
    rules: ["RULE-GOV-001"],
    sources: ["KB-GOV-002"],
    outcome: { en: "Action is hidden and audit event records denied scope.", ar: "يتم إخفاء الإجراء ويسجل التدقيق النطاق المرفوض." },
    nextAction: { en: "Route to approver", ar: "توجيه إلى المعتمد" },
    status: "Ready",
  },
  {
    id: "SCN-012",
    title: { en: "Emergency authority registry is stale", ar: "سجل جهة الطوارئ قديم" },
    persona: "Control room",
    workflow: "Alerts and emergencies",
    trigger: { en: "Authority contact has not been validated recently.", ar: "جهة الاتصال المخولة لم يتم التحقق منها مؤخراً." },
    rules: ["RULE-EMG-003", "RULE-EMG-001"],
    sources: ["KB-EMG-003", "KB-EMG-001"],
    outcome: { en: "MediaGPT requires manual validation before queueing the alert.", ar: "يتطلب MediaGPT تحققاً يدوياً قبل إدراج التنبيه." },
    nextAction: { en: "Validate authority", ar: "التحقق من الجهة" },
    status: "Ready",
  },
  {
    id: "SCN-013",
    title: { en: "Critical emergency template is auto-applied", ar: "تطبيق قالب طوارئ حرج تلقائياً" },
    persona: "Control room",
    workflow: "Alerts and emergencies",
    trigger: { en: "Critical alert content uses the wrong visual severity.", ar: "محتوى تنبيه حرج يستخدم شدة بصرية خاطئة." },
    rules: ["RULE-EMG-004", "RULE-EMG-002"],
    sources: ["KB-EMG-004", "KB-EMG-002"],
    outcome: { en: "MediaGPT proposes the approved layout and asks operator to confirm.", ar: "يقترح MediaGPT التخطيط المعتمد ويطلب تأكيد المشغل." },
    nextAction: { en: "Apply emergency template", ar: "تطبيق قالب الطوارئ" },
    status: "Ready",
  },
  {
    id: "SCN-014",
    title: { en: "Warranty exchange prevents unnecessary purchase order", ar: "استبدال الضمان يمنع أمر شراء غير ضروري" },
    persona: "Network operations",
    workflow: "Network and Devices",
    trigger: { en: "Router fails while warranty exchange is available.", ar: "يفشل الراوتر بينما الاستبدال بالضمان متاح." },
    rules: ["RULE-NET-004"],
    sources: ["KB-NET-004"],
    outcome: { en: "AI recommends exchange path and reserves technician dispatch after part confirmation.", ar: "يوصي الذكاء بمسار الاستبدال ويحجز إرسال الفني بعد تأكيد القطعة." },
    nextAction: { en: "Use warranty exchange", ar: "استخدام استبدال الضمان" },
    status: "Ready",
  },
  {
    id: "SCN-015",
    title: { en: "Stale telemetry reduces confidence before action", ar: "قياسات قديمة تخفض الثقة قبل الإجراء" },
    persona: "Technical owner",
    workflow: "Edge and Compute",
    trigger: { en: "Edge telemetry stops but asset still appears live.", ar: "تتوقف قياسات الحافة بينما يظهر الأصل مباشراً." },
    rules: ["RULE-NET-003", "RULE-INT-001"],
    sources: ["KB-NET-003", "KB-INT-003"],
    outcome: { en: "Confidence is lowered, owner is notified and automated proof decision is paused.", ar: "تُخفض الثقة ويُخطر المالك ويتوقف قرار الإثبات الآلي مؤقتاً." },
    nextAction: { en: "Refresh edge telemetry", ar: "تحديث قياسات الحافة" },
    status: "Ready",
  },
  {
    id: "SCN-016",
    title: { en: "Make-good recommendation after proof shortfall", ar: "توصية تعويض بعد نقص إثبات التشغيل" },
    persona: "Finance and audit",
    workflow: "Proof-of-play reconciliation",
    trigger: { en: "Contracted proof threshold is missed.", ar: "لم يتحقق حد الإثبات المتعاقد عليه." },
    rules: ["RULE-POP-002", "RULE-POP-001"],
    sources: ["KB-POP-002", "KB-POP-001"],
    outcome: { en: "MediaGPT calculates settlement impact and proposes make-good slots.", ar: "يحسب MediaGPT أثر التسوية ويقترح خانات تعويض." },
    nextAction: { en: "Offer make-good", ar: "تقديم تعويض إعلاني" },
    status: "Ready",
  },
  {
    id: "SCN-017",
    title: { en: "ERP PO update notifies O&M owner", ar: "تحديث أمر شراء ERP يرسل إشعاراً لمالك التشغيل والصيانة" },
    persona: "Technical owner",
    workflow: "Integrations",
    trigger: { en: "Supplier changes expected delivery date for critical part.", ar: "المورد يغير موعد التسليم المتوقع لقطعة حرجة." },
    rules: ["RULE-INT-001", "RULE-NET-002"],
    sources: ["KB-INT-002", "KB-NET-002"],
    outcome: { en: "Network table updates, notification is sent and audit event is recorded.", ar: "يُحدث جدول الشبكة ويُرسل إشعار ويسجل حدث تدقيق." },
    nextAction: { en: "Notify owner", ar: "إخطار المالك" },
    status: "Ready",
  },
  {
    id: "SCN-018",
    title: { en: "AI skill run is draft until model metadata is complete", ar: "تشغيل المهارة يبقى مسودة حتى تكتمل بيانات النموذج" },
    persona: "Platform admin",
    workflow: "Skill Runs",
    trigger: { en: "Skill output has action but no model version or token estimate.", ar: "نتيجة المهارة لها إجراء دون إصدار نموذج أو تقدير رموز." },
    rules: ["RULE-AI-002", "RULE-AI-001"],
    sources: ["KB-AI-003", "KB-AI-001"],
    outcome: { en: "Operational execution stays disabled until governed metadata is present.", ar: "يبقى التنفيذ التشغيلي معطلاً حتى تتوفر بيانات الحوكمة." },
    nextAction: { en: "Complete AI run metadata", ar: "استكمال بيانات تشغيل الذكاء" },
    status: "Ready",
  },
];
